# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestBrewTap < Formula
  desc ""
  homepage "https://github.com/canoypa/test-brew-tap"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/canoypa/test-brew-tap/releases/download/v0.0.2/test-brew-tap_0.0.2_darwin_arm64.tar.gz"
      sha256 "c4c87933de5e455733b00dfa13e115a4d077220b62a3a310faf5b7d22d9aaad1"

      def install
        bin.install "test-brew-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/canoypa/test-brew-tap/releases/download/v0.0.2/test-brew-tap_0.0.2_darwin_amd64.tar.gz"
      sha256 "fbf28552547d9d4aa27afb393c11595a0a2e06cc32a97f80b513fdca44afc626"

      def install
        bin.install "test-brew-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/canoypa/test-brew-tap/releases/download/v0.0.2/test-brew-tap_0.0.2_linux_amd64.tar.gz"
      sha256 "eb1b490fa53c93a9cb5f1fbb487b3029fd08fce26700b0c18c0b2d83c4a73794"

      def install
        bin.install "test-brew-tap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/canoypa/test-brew-tap/releases/download/v0.0.2/test-brew-tap_0.0.2_linux_arm64.tar.gz"
      sha256 "f8a80519647fb1880d302931fff3f0ad54f0e74ca35001f1c41e0b2424de6a5b"

      def install
        bin.install "test-brew-tap"
      end
    end
  end
end
